export const PAUSE_DIALOG_ZOMBIE_ANIMATION_PATH = 'animations/zombie_paper'
export const READY_SET_PLANT_ANIMATION_PATH = 'animations/startreadysetplant'
export const FINAL_WAVE_ANIMATION_PATH = 'animations/finalwave'
export const SILVER_COIN_ANIMATION_PATH = 'animations/coin_silver'
export const GOLD_COIN_ANIMATION_PATH = 'animations/coin_gold'
export const DIAMOND_ANIMATION_PATH = 'animations/diamond'

export const GAME_TEXTURES = [
    'background1',
    'background1unsodded',
    'seedbank',
    'conveyorbelt_backdrop',
    'conveyorbelt',
    'seeds',
    'seedpacket_larger',
    'particles/seedpacketflash',
    'particles/seedpacketglow',
    'particles/awardpickupglow',
    'particles/star40',
    'particles/awardrays_star',
    'particles/awardrays1',
    'particles/awardrays2',
    'particles/awardglow',
    'particles/downarrow',
    'dirtsmall',
    'particles/zombiehead',
    'particles/zombiearm',
    'zombie_flag3',
    'particles/pea_splats',
    'particles/pea_particles',
    'particles/snowpea_splats',
    'particles/snowpea_particles',
    'particles/explosioncloud',
    'particles/explosionpowie',
    'packet_plants',
    'packet_plants_cached',
    'plant_previews_cached',
    'wallnut_bowlingstripe',
    'zombie_cone3',
    'zombie_bucket3',
    'shovelbank',
    'shovel',
    'shovel_hi_res',
    'peashooter_head',
    'wallnut_cracked1',
    'wallnut_cracked2',
    'store_speechbubble2',
    'coinbank',
    'coinglow',
    'coin_black',
    'coin_black_gold',
    'coin_shading',
    'coin_silver_dollar',
    'coin_silver2',
    'coin_gold_dollar',
    'coin_gold2',
    'diamond',
    'diamond_shine1',
    'diamond_shine2',
    'diamond_shine3',
    'diamond_shine4',
    'diamond_shine5',
    'projectilepea',
    'projectilesnowpea',
    'pea_shadows',
    'plantshadow',
    'lawnmower_cached',
    'sod1row',
    'sod3row',
    'finalwave',
    'flagmeter',
    'flagmeterparts',
    'flagmeterlevelprogress',
    'background1_gameover_interior_overlay',
    'background1_gameover_mask',
    'zombieswon',
]
