import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import { resolve } from 'node:path'

const source = (file: string) => readFileSync(resolve(process.cwd(), file), 'utf8')

test('Adventure 1-1 presentation waits for entity creation and redraws restored HUD state', () => {
    const entities = source('assets/scripts/client/showcase/Adventure11EntityRenderer.ts')
    const particles = source('assets/scripts/client/showcase/Adventure11ParticlePresenter.ts')
    const view = source('assets/scripts/client/showcase/Adventure11View.ts')
    const showcase = source('assets/scripts/client/showcase/IntegratedAdventure11Showcase.ts')
    const input = source('assets/scripts/client/showcase/Adventure11InputPresenter.ts')
    const hud = source('assets/scripts/client/showcase/Adventure11HudPresenter.ts')
    const audio = source('assets/scripts/client/showcase/Adventure11AudioPresenter.ts')
    const end = source('assets/scripts/client/showcase/Adventure11EndPresenter.ts')
    const probe = source('assets/scripts/app/IntegratedAdventure11Probe.ts')
    const ui = source('assets/scripts/ui/UIController/UIController.ts')

    assert.match(entities, /async snapshot\(\)[^{]*\{\s*await Promise\.all\(this\.creationTasks\.values\(\)\)/)
    assert.match(view, /const \[entities, particles\] = await Promise\.all\(\[\s*this\.entityRenderer\.snapshot\(\),\s*this\.particles\.snapshot\(\)/)
    assert.match(particles, /await Promise\.all\(v2Players\.map\(player => player\.whenReady\(\)\)\)/)
    assert.match(particles, /name: snapshot\.playback\.id === 'pvz:seedpacketflash'[\s\S]*?parent,/)
    assert.match(view, /this\.end\.sync\(snapshot, events\)\s*for \(const item of snapshot\.items\) this\.end\.syncAward\(item, snapshot\.levelId\)/)
    assert.match(showcase, /const adventure11 = await this\.view\.snapshot\(/)
    assert.match(showcase, /this\.snapshotting = true\s*this\.input\.suspend\(\)\s*try \{/)
    assert.match(showcase, /finally \{\s*this\.snapshotting = false\s*if \(!this\.game\.render\(\)\.paused\) this\.input\.resume\(\)/)
    assert.match(showcase, /if \(this\.snapshotting \|\| this\.completing \|\| this\.gameOverNotified \|\| !this\.game/)
    assert.match(input, /private enabled = false/)
    assert.match(input, /if \(!this\.enabled \|\| !this\.view\.introComplete\) return/)
    assert.match(input, /const extra = definition \? 15 : 0/)
    assert.match(hud, /this\.syncSun\(world\.sun\)/)
    assert.match(hud, /this\.syncSeedPacket\(world, \[\], this\.lastIntroComplete, false\)/)
    assert.match(hud, /const visible = introComplete && snapshot\.result !== 'lost'/)
    assert.match(hud, /name: 'ParticleSystem_seedpacketflash'/)
    assert.match(audio, /case 'projectileFired': void SoundLoader\.playFoley\(SoundEffect\.Throw, 10\)/)
    assert.match(showcase, /if \(!this\.lifecycle\.onComplete\) return/)
    assert.match(showcase, /snapshot\.result === 'lost'[\s\S]*?this\.lifecycle\.onGameOver/)
    assert.match(showcase, /this\.game\.render\(\)\.paused\) return/)
    assert.match(end, /graphics\.fillColor = new Color\(255, 255, 255, alpha\)/)
    assert.match(end, /graphics\.fillRect\(-400, -300, 800, 600\)/)
    assert.doesNotMatch(view, /ProfileStore/)
    assert.match(view, /static async create\(root: Node, content: LoadedContent, playerName: string\)/)
    assert.match(probe, /const playerName = ProfileStore\.getCurrentProfile\(\)\?\.name \|\| 'Player'/)
    assert.match(probe, /Adventure11View\.create\(root, content, playerName\)/)
    assert.match(ui, /createIntegratedAdventure11Controller\(this\.uiRoot, \{/)
    assert.match(ui, /if \(level\.id === ADVENTURE_1_1\.id\)/)
    assert.match(ui, /controller\.play\(\{ forceNewGame: options\.forceNewGame \}\)/)
    assert.match(ui, /showAwardScreen\(\{ kind: 'seed', seedType: 'sunflower' \}/)
    assert.match(ui, /_handleIntegratedAdventure11GameOver/)
    assert.match(ui, /installIntegratedAdventure11Probe\(this\._integratedAdventure11\)/)
})
