import type {
    BoardGeometry,
    LevelDefinition,
    PlantDefinition,
    SeedDefinition,
    ZombieDefinition,
} from './GameTypes'

export const GAME_TICK_SECONDS = 0.01
export const GAME_SPEED = 1

export const DAY_GEOMETRY: BoardGeometry = {
    width: 800,
    height: 600,
    lawnXMin: 40,
    lawnYMin: 80,
    gridWidth: 80,
    gridHeight: 100,
    cols: 9,
    rows: 5,
    seedBankRect: { x: 0, y: 0, width: 446, height: 87 },
    menuButtonRect: { x: 680, y: 0, width: 110, height: 40 },
    gridToPixel(col: number, row: number) {
        return {
            x: col * 80 + 40,
            y: row * 100 + 80,
        }
    },
    pixelToGrid(x: number, y: number) {
        if (x < 40 || y < 80) return null
        const col = Math.max(0, Math.min(8, Math.floor((x - 40) / 80)))
        const row = Math.max(0, Math.min(4, Math.floor((y - 80) / 100)))
        return { col, row }
    },
    plantingPixelToGrid(x: number, y: number) {
        return this.pixelToGrid(x, y)
    },
    rowZ(row: number) {
        return 100 + row * 20
    },
}

export const SEED_DEFINITIONS: Record<string, SeedDefinition> = {
    peashooter: {
        id: 'peashooter',
        plantType: 'peashooter',
        cost: 100,
        cooldownTicks: 750,
        packetSprite: 'seedpacket_larger',
        cursorSprite: 'peashooter_head',
        placement: 'ground',
    },
    sunflower: {
        id: 'sunflower',
        plantType: 'sunflower',
        cost: 50,
        cooldownTicks: 750,
        packetSprite: 'seedpacket_larger',
        cursorSprite: 'sunflower_head',
        placement: 'ground',
    },
    cherrybomb: {
        id: 'cherrybomb',
        plantType: 'cherrybomb',
        cost: 150,
        cooldownTicks: 5000,
        packetSprite: 'seedpacket_larger',
        cursorSprite: 'cherrybomb_left1',
        placement: 'ground',
    },
    wallnut: {
        id: 'wallnut',
        plantType: 'wallnut',
        cost: 50,
        cooldownTicks: 3000,
        packetSprite: 'seedpacket_larger',
        cursorSprite: 'wallnut_body',
        placement: 'ground',
    },
    potatomine: {
        id: 'potatomine',
        plantType: 'potatomine',
        cost: 25,
        cooldownTicks: 3000,
        packetSprite: 'seedpacket_larger',
        cursorSprite: 'potatomine_body',
        placement: 'ground',
    },
    snowpea: {
        id: 'snowpea',
        plantType: 'snowpea',
        cost: 175,
        cooldownTicks: 750,
        packetSprite: 'seedpacket_larger',
        cursorSprite: 'snowpea_head',
        placement: 'ground',
    },
    chomper: {
        id: 'chomper',
        plantType: 'chomper',
        cost: 150,
        cooldownTicks: 750,
        packetSprite: 'seedpacket_larger',
        cursorSprite: 'chomper_topjaw',
        placement: 'ground',
    },
    repeater: {
        id: 'repeater',
        plantType: 'repeater',
        cost: 200,
        cooldownTicks: 750,
        packetSprite: 'seedpacket_larger',
        cursorSprite: 'peashooter_head',
        placement: 'ground',
    },
}

export const PLANT_DEFINITIONS: Record<string, PlantDefinition> = {
    peashooter: {
        id: 'peashooter',
        maxHealth: 300,
        attackCadenceTicks: 150,
        firstAttackDelayTicks: 75,
        shootingAnimationTicks: 33,
        projectileType: 'pea',
        projectileOffsetX: 56,
        projectileOffsetY: 10,
        animationPath: 'animations/peashootersingle',
        bodyRect: { x: 10, y: 0, width: 60, height: 80 },
    },
    sunflower: {
        id: 'sunflower',
        maxHealth: 300,
        attackCadenceTicks: 2500,
        firstAttackDelayTicks: 2500,
        shootingAnimationTicks: 0,
        projectileType: 'pea',
        projectileOffsetX: 0,
        projectileOffsetY: 0,
        animationPath: 'animations/sunflower',
        bodyRect: { x: 10, y: 0, width: 60, height: 80 },
    },
    cherrybomb: {
        id: 'cherrybomb',
        maxHealth: 300,
        attackCadenceTicks: 0,
        firstAttackDelayTicks: 0,
        shootingAnimationTicks: 0,
        projectileType: 'pea',
        projectileOffsetX: 0,
        projectileOffsetY: 0,
        animationPath: 'animations/cherrybomb',
        bodyRect: { x: 10, y: 0, width: 60, height: 80 },
    },
    wallnut: {
        id: 'wallnut',
        maxHealth: 4000,
        attackCadenceTicks: 0,
        firstAttackDelayTicks: 0,
        shootingAnimationTicks: 0,
        projectileType: 'pea',
        projectileOffsetX: 0,
        projectileOffsetY: 0,
        animationPath: 'animations/wallnut',
        bodyRect: { x: 10, y: 0, width: 60, height: 80 },
    },
    snowpea: {
        id: 'snowpea',
        maxHealth: 300,
        attackCadenceTicks: 150,
        firstAttackDelayTicks: 75,
        shootingAnimationTicks: 33,
        projectileType: 'snowpea',
        projectileOffsetX: 56,
        projectileOffsetY: 10,
        animationPath: 'animations/snowpea',
        bodyRect: { x: 10, y: 0, width: 60, height: 80 },
    },
    potatomine: {
        id: 'potatomine',
        maxHealth: 300,
        attackCadenceTicks: 0,
        firstAttackDelayTicks: 0,
        shootingAnimationTicks: 0,
        projectileType: 'pea',
        projectileOffsetX: 0,
        projectileOffsetY: 0,
        animationPath: 'animations/potatomine',
        bodyRect: { x: 10, y: 0, width: 60, height: 80 },
    },
    chomper: {
        id: 'chomper',
        maxHealth: 300,
        attackCadenceTicks: 0,
        firstAttackDelayTicks: 0,
        shootingAnimationTicks: 0,
        projectileType: 'pea',
        projectileOffsetX: 0,
        projectileOffsetY: 0,
        animationPath: 'animations/chomper',
        bodyRect: { x: 10, y: 0, width: 60, height: 80 },
    },
    repeater: {
        id: 'repeater',
        maxHealth: 300,
        attackCadenceTicks: 150,
        firstAttackDelayTicks: 75,
        shootingAnimationTicks: 26,
        projectileType: 'pea',
        projectileOffsetX: 56,
        projectileOffsetY: 10,
        animationPath: 'animations/peashooter',
        bodyRect: { x: 10, y: 0, width: 60, height: 80 },
    },
}

const NORMAL_ZOMBIE_BODY_RECT = { x: 36, y: 0, width: 42, height: 115 }
const NORMAL_ZOMBIE_ATTACK_RECT = { x: 20, y: 0, width: 50, height: 115 }
const NORMAL_ZOMBIE_ANIMATION_PATH = 'animations/zombie'

export const ZOMBIE_DEFINITIONS: Record<string, ZombieDefinition> = {
    normal: {
        id: 'normal',
        maxHealth: 270,
        helmType: 'none',
        helmHealth: 0,
        shieldType: 'none',
        shieldHealth: 0,
        velocityXMin: 0.23,
        velocityXMax: 0.32,
        animationPath: NORMAL_ZOMBIE_ANIMATION_PATH,
        defaultAnimation: 'anim_walk',
        bodyRect: NORMAL_ZOMBIE_BODY_RECT,
        attackRect: NORMAL_ZOMBIE_ATTACK_RECT,
        hasFlag: false,
        hasFloat: false,
    },
    flag: {
        id: 'flag',
        maxHealth: 270,
        helmType: 'none',
        helmHealth: 0,
        shieldType: 'none',
        shieldHealth: 0,
        velocityXMin: 0.45,
        velocityXMax: 0.45,
        animationPath: NORMAL_ZOMBIE_ANIMATION_PATH,
        defaultAnimation: 'anim_walk',
        bodyRect: NORMAL_ZOMBIE_BODY_RECT,
        attackRect: NORMAL_ZOMBIE_ATTACK_RECT,
        hasFlag: true,
        hasFloat: false,
    },
    'traffic-cone': {
        id: 'traffic-cone',
        maxHealth: 270,
        helmType: 'traffic-cone',
        helmHealth: 370,
        shieldType: 'none',
        shieldHealth: 0,
        velocityXMin: 0.23,
        velocityXMax: 0.32,
        animationPath: NORMAL_ZOMBIE_ANIMATION_PATH,
        defaultAnimation: 'anim_walk',
        bodyRect: NORMAL_ZOMBIE_BODY_RECT,
        attackRect: NORMAL_ZOMBIE_ATTACK_RECT,
        hasFlag: false,
        hasFloat: false,
    },
    bucket: {
        id: 'bucket',
        maxHealth: 270,
        helmType: 'bucket',
        helmHealth: 1100,
        shieldType: 'none',
        shieldHealth: 0,
        velocityXMin: 0.23,
        velocityXMax: 0.32,
        animationPath: NORMAL_ZOMBIE_ANIMATION_PATH,
        defaultAnimation: 'anim_walk',
        bodyRect: NORMAL_ZOMBIE_BODY_RECT,
        attackRect: NORMAL_ZOMBIE_ATTACK_RECT,
        hasFlag: false,
        hasFloat: false,
    },
    'ducky-tube': {
        id: 'ducky-tube',
        maxHealth: 270,
        helmType: 'none',
        helmHealth: 0,
        shieldType: 'none',
        shieldHealth: 0,
        velocityXMin: 0.23,
        velocityXMax: 0.32,
        animationPath: NORMAL_ZOMBIE_ANIMATION_PATH,
        defaultAnimation: 'anim_swim',
        bodyRect: NORMAL_ZOMBIE_BODY_RECT,
        attackRect: NORMAL_ZOMBIE_ATTACK_RECT,
        hasFlag: false,
        hasFloat: true,
    },
}

export const ADVENTURE_1_1: LevelDefinition = {
    id: 'adventure-1-1',
    adventureLevel: 1,
    background: 'day',
    activeRows: [2],
    startingSun: 150,
    seedPackets: ['peashooter'],
    zombieWaves: [
        { zombies: ['normal'] },
        { zombies: ['normal'] },
        { zombies: ['normal'] },
        { zombies: ['normal', 'normal'] },
    ],
    tutorialAdvice: [
        'Click on a seed packet to pick it up!',
    ],
}
